# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      - feat/sql-server
  paths:
    include:
      - docker/sql-server



pool:
  vmImage: ubuntu-latest

variables:
  imageName: sql-server-fiap


steps:
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'caiomaia3/sql-server-fiap'
    command: 'build'
    Dockerfile: '**/docker/sql-server/Dockerfile'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
