# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
        - docker/sql-server/**
    exclude:
      - docker/sql-server/README.md
  
pr:
  branches:
    include:
      - main
  paths:
    include:
      - docker/sql-server/**
    exclude:
      - docker/sql-server/README.md

pool:
  vmImage: ubuntu-latest


steps:
- task: Docker@2
  displayName: Build Docker Image - Docker Hub
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'caiomaia3/sql-server-fiap'
    command: 'buildAndPush'
    Dockerfile: '**/docker/sql-server/Dockerfile'
    
- task: Docker@2
  displayName: Build Docker Image - Azure Container Registry
  inputs:
    containerRegistry: 'ACR FIAP'
    repository: 'fiap/sql-server-fiap'
    command: 'buildAndPush'
    Dockerfile: '**/docker/sql-server/Dockerfile'
    tags: 'latest'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
