global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'webapp'
    static_configs:
      - targets: ['fiap-webapp-76a464e5dc4e49de8fc674e0db728386.azurewebsites.net']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']