apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus-fiap-container.eastus.azurecontainer.io:9090
    isDefault: true
    version: 1
    editable: true
