services:
  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    volumes:
     - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
     - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
#      - ./grafana/dashboard_setup.json:/etc/grafana/provisioning/dashboards/imported-dashboards/dashboard_setup.json
      - ./config/prometheus-datasource.yml:/etc/grafana/provisioning/datasources/prometheus-datasource.yml
      - ./config/prometheus-dashboard.yml:/etc/grafana/provisioning/dashboards/prometheus-dashboard.yml
    ports:
     - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    networks:
      - monitoring
    
networks:
  monitoring:
    driver: bridge