services:
  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    volumes:
     - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
     - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:7.2.1
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - ./prometheus-datasource.yml:/etc/grafana/provisioning/datasources/prometheus-datasource.yml
      - ./prometheus-dashboard.yml:/etc/grafana/provisioning/dashboards/prometheus-dashboard.yml
    ports:
     - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring


    
networks:
  monitoring:
    driver: bridge