name: Build and Deploy Prometheus and Grafana

on:
  push:
    branches:
      - feat/monitoring-settings
  workflow_dispatch:
  
jobs:
  upload:
    name: Upload Files
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.__clientidstorage__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}
          
