# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - fiap-webap-76a464e5dc4e49de8fc674e0db728386

on:
  push:
    branches:
      - feat/integration-test
    paths-ignore:
      - 'docker/**'
      - 'Docs/**'
      - 'azure-pipelines.yml'
      - 'README.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./ContactsManager/ContactsManagement.Api/ContactsManagement.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./ContactsManager/ContactsManagement.Api/ContactsManagement.Api.csproj -c Release -o '${{env.DOTNET_ROOT}}\myapp'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
  
  unit-tests:
    runs-on: windows-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Run Unit Tests
        run: dotnet test ./ContactsManager/TestesUnitarios/TestesUnitarios.csproj

  deploy:
    runs-on: windows-latest
    needs: unit-tests
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fiap-webapp-76a464e5dc4e49de8fc674e0db728386'
          package: .
          
  integration-tests:
    runs-on: windows-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Run Unit Tests
        run: dotnet test ./ContactsManager/TestesIntergacao/TestesIntergacao.csproj